### ISSUE TITLE
We should be able to define the folder structure when creating files using the Artisan commands

### ISSUE THREAD

**Issue by jesuskevin** [MiguelMateoTavarez/base_modular_laravel_project#2]
Example:
`php artisan make:module-interface ModuleName FolderName/ResourceInterface`

NOTE
If the folder does not exits, the system should be able to create it....

**Comment by MiguelMateoTavarez** [comment]
[Add custom directory option to create commands](https://github.com/MiguelMateoTavarez/base_modular_laravel_project/pull/5)
